### ISSUE TITLE
'MetricPerClass' object has no attribute 'category'

### ISSUE THREAD

**Issue by saintrealchoi** [yfpeng/object_detection_metrics#2]
First of all, Thank you for implementation about metrics.

and i have an error like title 
about README.md
ap, precision, recall, tp, fp, etc section

for cls, metric in results.items():
    **label = metric.category**
    print('ap', metric.ap)
    print('precision', metric.precision)
    print('interpolated_recall', metric.interpolated_recall)
    print('interpolated_precision', metric.interpolated_precision)
    print('tp', metric.tp)
    print('fp', metric.fp)
    print('num_groundtruth', metric.num_groundtruth)
    print('num_detection', metric.num_detection)

**metric.category** should be changed **metric.label**
because metric don't have category

Sincerely

**Comment by yfpeng** [comment]
Thank you.
